### ISSUE TITLE
Permission denied (publickey,keyboard-interactive).

### ISSUE THREAD

**Issue by 3nd0y** [Magisk-Modules-Repo/ssh#17]
After installation, i generate key and rsa_id in root/authorized_keys and shell/authorized_keys. But still i can't connect SSH from remote and it said _Permission denied (publickey,keyboard-interactive)_. Do you have any idea?

**Comment by lemmy04** [comment]
you have to put your public key into those two files, not your private key.

**Comment by kdb424** [comment]
chmod 600 authorized_keys
It's very picky about this for security reasons.

**Comment by thekiefs** [comment]
I have this same error. I put id_rsa.pub in /data/ssh/root/.ssh/authorized_keys, then ran chmod 600 authorized_keys and I'm still having problems. Any help? @kdb424 @lemmy04

**Comment by 3nd0y** [comment]
@lemmy04 yes i put the public key, also chmod 600 as suggest @kdb424 but error still occurred. 

I am use oreo Android 8.0, stock rom.

**Comment by WaytrueDeng** [comment]
I have met the same problem, and I did everything i colud.but it still permission denied.I am using the EvolutionX 4.1 for OnePlus7pro.

**Comment by wjes** [comment]
I had the same problem with LineageOS 17.1 in Samsung Galaxy J7. Be 100% sure the permissions and ownership are correct before trying anything else (since `StrictModes` is set to `yes` by default in `sshd_config`)

In the *client*
- `chmod 700 .ssh`
- `chmod 600 .ssh/id_rsa` 
- `chown -R <username>:<username> .ssh`

In the *server*
- `chmod 700 .ssh`
- `chmod 600 .ssh/authorized_keys`
- `chown -R <username>:<username> .ssh`

Also check the integrity of your key(s) in `authorized_keys` (no line breaks withing the keys and stuff)

If the problem persists check [SELinux](https://stackoverflow.com/questions/6377009/adding-public-key-to-ssh-authorized-keys-does-not-log-me-in-automatically#answer-21636460) 
- `restorecon -R -v /<username>/.ssh`

You could try setting `StrictModes` to `no` and turning SELinux off with `setenforce 0` to see if the problem is beyond that boundaries. Hope it helps :)

**Comment by cizordj** [comment]
@wjes Thanks for the tip! It worked on my Samsung running stock ROM. I would like to write an addendum for your comment.

In the _server_ if the folder is `/data/ssh/shell/.ssh` you must change the owner to the user **shell**, like this:
`chown -R shell:shell /data/ssh/shell/.ssh/`
and for the root _authorized_keys_
`chown -R root:root /data/ssh/root/.ssh/`

**Comment by 3nd0y** [comment]
I see, so i need put the authorized_keys in `/data/ssh/root/.ssh/` or `/data/ssh/shell/.ssh/` in android that's why everytime i need try to login from client it's never work, because what i did is put like `/data/ssh/root/authorized_keys` or `/data/ssh/shell/authorized_keys`. Thanks all. I'll close this
